{% set version = "0.6.1" %}

package:
  name: discretize
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/discretize/discretize-{{ version }}.tar.gz
  sha256: 379ba5da7042489c005170eb69889cbebd3e705184fc323ce553aededa46e4d5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - cython >=0.2
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13
    - properties
    - vectormath

test:
  imports:
    - discretize

about:
  home: http://github.com/simpeg/discretize
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Discretization tools for finite volume and inverse problems

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
