{% set version = "0.7.0" %}

package:
  name: discretize
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/discretize/discretize-{{ version }}.tar.gz
  sha256: f8d0c9e3718d535ee72abbfa74f7d18d2234bba016abcecb5c46e2c4a79011f4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - cython >=0.2
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13

test:
  imports:
    - discretize

about:
  home: http://github.com/simpeg/discretize
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Discretization tools for finite volume and inverse problems

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
