{% set version = "0.9.0" %}

package:
  name: discretize
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/discretize/discretize-{{ version }}.tar.gz
  sha256: 4f1f2d0e88c98a302c660ab2a6836c0b6c43994dc02c8f5f9318d3815529fcb0

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - python
    - pip
    - numpy
    - cython >=0.2
    - setuptools_scm
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13

test:
  imports:
    - discretize
  requires:
    - setuptools  # [py<38]
  commands:
    - python -c "import discretize; print(discretize.__version__)"
    - python -c "from importlib.metadata import version; print(version('discretize'))"  # [py>=38]
    - python -c "from pkg_resources import get_distribution; print(get_distribution('discretize').version)"  # [py<38]

about:
  home: http://github.com/simpeg/discretize
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Discretization tools for finite volume and inverse problems

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
