{% set version = "0.4.11" %}

package:
  name: discretize
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/discretize/discretize-{{ version }}.tar.gz
  sha256: a91fc5b32f83ade952d6e02f88ca6afb0d0b29a0feebf78c87b44b37ccd79e77

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - cython >=0.2
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13
    - pymatsolver >=0.1.2
    - properties
    - vectormath

test:
  imports:
    - discretize

about:
  home: http://github.com/simpeg/discretize
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Discretization tools for finite volume and inverse problems

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
