{% set version = "0.7.4" %}

package:
  name: discretize
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/discretize/discretize-{{ version }}.tar.gz
  sha256: 52146c50ca4c809037ee64dd5b1193f42bcb349dac345b3fdbecea5f890fbbfc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - python
    - pip
    - numpy
    - cython >=0.2
    - setuptools_scm
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13

test:
  imports:
    - discretize
  commands:
     - python -c "import discretize; print(discretize.__version__)"
     - python -c "from importlib.metadata import version; print(version('discretize'))"

about:
  home: http://github.com/simpeg/discretize
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Discretization tools for finite volume and inverse problems

extra:
  recipe-maintainers:
    - lheagy
    - jcapriot
