travis:
  secure:
    BINSTAR_TOKEN: b98nEohI0jY6xi6/NpT/u9jaIBNyablV58LBa4VrB+XUHhMK5YYhhjiyIg8o8QHHGr8wZkn76Ail7U8eUNyIUZWfq5h6D/izxPg8IhNaoG2lTrI8fmlRLWg7f2irN0fo6WfGt2A0T8lAgP4wnVRREG5E+hExO5adTAXYJbkq8RLa4Aq+VJ/C4XhkUwa08a+jdn03Z24nMns/pi7R/w7lqKKFe759ISZugubdOu4f3VceylMEk7b95WN+BeXfNQI5sFrXcubYqJKRc8rmNSMAZQitp/18oQ6g/V8t7C2MRr5rm0YrlU121WGLvolZuUSCq49xPZczUHHmzQxOtzY4Ij4yaStLWtH8pN27fYIeMlCOcwgGUiMosG8JA0grRUhKpjzGS1chT8xZatRojm6Gcl95W3yVVQuvgj63L2Xz1KjjKE3RC4Ya29wEMnIozHhFtGpDPVhctVre0PpJimeEx8EZhBV99PO4Ud6kb3tPFBpQYRWDkDOsdrr+VGRx3KpxmgV6yyBwTJvY3DQuK4ciXeENhtcarefjUM+T2aE+Lgzzaq3JJbfxUjTTbaXgOjpVP9zmfphqz8kDxWS3U+FV0n1oeJhyVnQ5OqtuAb6yS2SgoSGe4DnrI6/YmXhx7JOnNWjmOg7TjKsLudYgtNJ4uei5lssyMZE4nr37Z/jnmX4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
bot:
  automerge: true
